# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-14 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodstype',
            name='picture',
            field=models.ImageField(null=True, upload_to='static/upload/goodtype', verbose_name='类型图片'),
        ),
    ]
